# AT & T assembly

number			= [ "0x" ], "[0-9]+";
identifier		= "[a-zA-Z][a-zA-Z0-9]*";
register		= "%", identifier;
immediate		= "$", number;
whitespace		= "[ \t]+";
line_terminator	= "[\n;]+";
comment			= "#.*";

operand = register | immediate | number;

operand_list = operand, {",", operand};

instruction	= identifier, [operand_list];

instruction_list = (instruction | comment), {line_terminator, instruction};
