number			= [ "0x" ], digit, {digit};
identifier		= letter, { letter | digit };
register		= "%", identifier;
immediate		= "$", number;
whitespace		= { " " | "\t" };
line_terminator	= { "\n" | ";" };

operand = register | immediate | number;

operand_list = [whitespace], operand, {",", [whitespace], operand};

instruction	= identifier, [operand_list];

instruction_list = [whitespace], instruction, {line_terminator, [whitespace], instruction};
