number			= [ "0x" ], "[0-9]+";
identifier		= "[a-zA-Z][a-zA-Z0-9]*";
register		= "%", identifier;
immediate		= "$", number;
whitespace		= "[ \t]+";
line_terminator	= "[\n;]+";

operand = register | immediate | number;

operand_list_continue = ",", operand;

operand_list = operand, {operand_list_continue};

instruction	= identifier, [operand_list];

instruction_list_continue = line_terminator, instruction;

instruction_list = instruction, {instruction_list_continue};
