
comment = "\/\/[^\n]*|\/\*[\s\S]*?\*\/";
whitespace = '\s+';

##ignore comment whitespace

# String and character constants

# Due to comments handling, we need to have a literal for the entire character constant
character_constant = "(u8|u|U|L)?'([^'\\\n]|\\['\"\\?abfnrtv]|\\[0-7]{1,3}|\\x[0-9A-Fa-f]+|\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8})*'";

string_literal = '(u8|u|U|L)?"([^"\\\n]|\\["\'\\?abfnrtv]|\\[0-7]{1,3}|\\x[0-9A-Fa-f]+|\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8})*"';

quote = "'";
