
# `punctuator` minus things used later (e.g. "any pp-token other than ...")
__punctuator_base = "\." | "->"
| "\+\+" | "--" | "&" | "\*" | "\+" | "-" | "~" | "!"
| "/" | "%" | "==" | "!=" | "\^" | "\|" | "&&" | "\|\|" | "\?" | ":" | "::" | ";" | "\.\.\."
| "=" | "\*=" | "/=" | "%=" | "\+=" | "-=" | "&=" | "\^=" | "\|="
| "," | "#" | "##"
| "%:" | "%:%:";

__punctuator_angle_brackets = "<<" | ">>" | "<" | ">" | "<=" | ">=" | "<<=" | ">>=" | "<:" | ":>" | "<%" | "%>";
__punctuator_grouping = "\[" | "\]" | "\(" | "\)" | "\{" | "\}";

punctuator =  __punctuator_base | __punctuator_angle_brackets | __punctuator_grouping;