# AT & T assembly

number          = "(0x)?\d+";
identifier      = "[a-zA-Z_]\w*";
register        = "%\w+";
immediate       = "\$(0x)?\d+";
whitespace      = "[ \t]+";
line_terminator = "[\n;]+";
comment         = "#.*";

##ignore whitespace line_terminator comment

operand = register | immediate | number;

operand_list = operand, {",", operand};

instruction	= identifier, operand_list?;

##root instruction
