name: Continuous Integration

on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:
    pull_request:

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install native build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget lsb-release gnupg software-properties-common
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 21
                  sudo apt-get install -y clang-21 llvm-21-dev libclang-21-dev

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: latest

            - name: Install dependencies
              run: npm install

            - name: Formatting
              run: npm run format:check

            - name: Linting
              run: npm run lint

            - name: Build TypeScript
              run: npm run build:ts

            - name: Build Native
              run: npm run build:native
