name: Release
on:
    release:
        types: [created]
    workflow_call:
        secrets:
            npm_token:
                required: true
jobs:
    ci:
        name: CI Checks
        uses: ./.github/workflows/ci.yaml
    release:
        runs-on: ubuntu-latest
        needs: ci
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install native build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget lsb-release gnupg software-properties-common
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 21
                  sudo apt-get install -y clang-21 llvm-21-dev libclang-21-dev

            - name: Setup npm authentication
              uses: actions/setup-node@v6
              with:
                  node-version: latest
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Publish
              run: npm publish --access=public --provenance
    docs:
        runs-on: ubuntu-latest
        name: Docs build and deploy
        permissions:
            contents: write
            id-token: write
            pages: write
        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: latest

            - name: Install dependencies
              run: npm install

            - name: Build docs
              run: npm run build:docs

            - name: Upload docs artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./docs

            - name: 'Deploy docs'
              id: deploy
              uses: actions/deploy-pages@v4
